global:
  scrape_interval: 15s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
  # Por si tienes el cadvisor - In case you have the cadvisor  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']